### ISSUE TITLE
Release version

### ISSUE THREAD

**Issue by abdul737** [Geebrox/react-g#2]
The project needs to be (e.g. v0.1.0) to let people download the built zip file to check its weight and contents. Also, the project should be posted for demo in GitHub pages. It will help people to trace and check the stability of the page run with these configuration settings

**Comment by ismoiliy98** [comment]
@abdul737 Do you think that we really need it for this project? There is nothing to demonstrate on the built react-g

**Comment by abdul737** [comment]
> @abdul737 Do you think that we really need it for this project? There is nothing to demonstrate on the built react-g

Well maybe we don't need github pages, but it would be great to be able to download zip file though, this way users. It demonstrates build size and content, for example how bundles are generated, how assets are distributed and maybe a content of the minified file could be interesting for someone who needs this boilerplate

**Comment by ismoiliy98** [comment]
@abdul737 Okay, will be implemented soon
